-- ============================================================
-- BizCatalyst — Supabase Database Schema
-- Run this in Supabase SQL Editor (https://supabase.com/dashboard)
-- ============================================================

-- ========================
-- 1. CONTACTS TABLE (CRM)
-- ========================
CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  company TEXT,
  phone TEXT,
  status TEXT DEFAULT 'lead' CHECK (status IN ('lead', 'customer', 'churned')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ========================
-- 2. DEALS TABLE (CRM Pipeline)
-- ========================
CREATE TABLE IF NOT EXISTS deals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id BIGINT REFERENCES contacts(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  value NUMERIC(12, 2) DEFAULT 0,
  stage TEXT DEFAULT 'prospecting' CHECK (stage IN ('prospecting', 'negotiation', 'won', 'lost')),
  expected_close_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ========================
-- 3. CAMPAIGNS TABLE
-- ========================
CREATE TABLE IF NOT EXISTS campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  channel TEXT DEFAULT 'email' CHECK (channel IN ('email', 'social', 'sms', 'ads')),
  budget NUMERIC(12, 2) DEFAULT 0,
  spent NUMERIC(12, 2) DEFAULT 0,
  leads_generated INT DEFAULT 0,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'paused', 'completed')),
  start_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ========================
-- 4. SCHEDULE EVENTS TABLE
-- ========================
CREATE TABLE IF NOT EXISTS schedule_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  event_date DATE NOT NULL,
  event_time TIME DEFAULT '09:00',
  duration_min INT DEFAULT 30,
  attendees TEXT,
  location TEXT,
  description TEXT,
  status TEXT DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ========================
-- 5. SITE STATS TABLE (Home Page)
-- ========================
CREATE TABLE IF NOT EXISTS site_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stat_key TEXT UNIQUE NOT NULL,
  stat_value INT DEFAULT 0,
  stat_label TEXT,
  stat_suffix TEXT DEFAULT '+',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ========================
-- ENABLE REALTIME ON ALL TABLES
-- ========================
ALTER PUBLICATION supabase_realtime ADD TABLE contacts;
ALTER PUBLICATION supabase_realtime ADD TABLE deals;
ALTER PUBLICATION supabase_realtime ADD TABLE campaigns;
ALTER PUBLICATION supabase_realtime ADD TABLE schedule_events;
ALTER PUBLICATION supabase_realtime ADD TABLE site_stats;

-- ========================
-- ROW LEVEL SECURITY (Allow public read/write for demo)
-- ========================
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE deals ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE schedule_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_stats ENABLE ROW LEVEL SECURITY;

-- Allow anonymous read access
CREATE POLICY "Allow public read contacts" ON contacts FOR SELECT USING (true);
CREATE POLICY "Allow public insert contacts" ON contacts FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update contacts" ON contacts FOR UPDATE USING (true);
CREATE POLICY "Allow public delete contacts" ON contacts FOR DELETE USING (true);

CREATE POLICY "Allow public read deals" ON deals FOR SELECT USING (true);
CREATE POLICY "Allow public insert deals" ON deals FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update deals" ON deals FOR UPDATE USING (true);
CREATE POLICY "Allow public delete deals" ON deals FOR DELETE USING (true);

CREATE POLICY "Allow public read campaigns" ON campaigns FOR SELECT USING (true);
CREATE POLICY "Allow public insert campaigns" ON campaigns FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update campaigns" ON campaigns FOR UPDATE USING (true);
CREATE POLICY "Allow public delete campaigns" ON campaigns FOR DELETE USING (true);

CREATE POLICY "Allow public read schedule_events" ON schedule_events FOR SELECT USING (true);
CREATE POLICY "Allow public insert schedule_events" ON schedule_events FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update schedule_events" ON schedule_events FOR UPDATE USING (true);
CREATE POLICY "Allow public delete schedule_events" ON schedule_events FOR DELETE USING (true);

CREATE POLICY "Allow public read site_stats" ON site_stats FOR SELECT USING (true);
CREATE POLICY "Allow public update site_stats" ON site_stats FOR UPDATE USING (true);

-- ========================
-- SEED DATA
-- ========================

-- Site Stats
INSERT INTO site_stats (stat_key, stat_value, stat_label, stat_suffix) VALUES
  ('active_businesses', 2500, 'Active Businesses', '+'),
  ('satisfaction_rate', 98, 'Satisfaction Rate', '%'),
  ('powerful_modules', 4, 'Powerful Modules', '+'),
  ('support_hours', 24, 'Support Hours', '/7');

-- Sample Contacts
INSERT INTO contacts (full_name, email, company, phone, status) VALUES
  ('Sarah Rodriguez', 'sarah@launchpad.com', 'LaunchPad Inc', '+1-555-0101', 'customer'),
  ('Marcus Kim', 'marcus@dataforge.io', 'DataForge', '+1-555-0102', 'customer'),
  ('Anika Patel', 'anika@targetflow.com', 'TargetFlow', '+1-555-0103', 'customer'),
  ('James Liu', 'james@scaleupai.com', 'ScaleUp AI', '+1-555-0104', 'lead'),
  ('Elena Vasquez', 'elena@brightpath.co', 'BrightPath Co', '+1-555-0105', 'lead'),
  ('David Okafor', 'david@nexusworks.io', 'NexusWorks', '+1-555-0106', 'customer'),
  ('Priya Sharma', 'priya@cloudnine.dev', 'CloudNine Dev', '+1-555-0107', 'lead'),
  ('Tom Henderson', 'tom@steelbridge.com', 'SteelBridge', '+1-555-0108', 'churned'),
  ('Lisa Chang', 'lisa@quantum.tech', 'Quantum Tech', '+1-555-0109', 'customer'),
  ('Robert Martinez', 'robert@innovate.co', 'Innovate Co', '+1-555-0110', 'lead');

-- Sample Deals
INSERT INTO deals (contact_id, title, value, stage, expected_close_date) VALUES
  (1, 'LaunchPad Enterprise License', 45000.00, 'won', '2026-06-15'),
  (2, 'DataForge Annual Contract', 32000.00, 'won', '2026-05-20'),
  (3, 'TargetFlow Platform Deal', 28000.00, 'negotiation', '2026-08-01'),
  (4, 'ScaleUp AI Integration', 55000.00, 'prospecting', '2026-09-15'),
  (5, 'BrightPath Starter Package', 8500.00, 'prospecting', '2026-08-30'),
  (6, 'NexusWorks Pro Upgrade', 22000.00, 'won', '2026-04-10'),
  (7, 'CloudNine Development Suite', 18000.00, 'negotiation', '2026-08-20'),
  (8, 'SteelBridge Renewal', 15000.00, 'lost', '2026-03-01'),
  (9, 'Quantum Tech Enterprise', 62000.00, 'negotiation', '2026-09-01'),
  (10, 'Innovate Co Starter Plan', 5000.00, 'prospecting', '2026-10-01');

-- Sample Campaigns
INSERT INTO campaigns (name, channel, budget, spent, leads_generated, status, start_date) VALUES
  ('Summer Product Launch', 'email', 5000.00, 3200.00, 145, 'active', '2026-06-01'),
  ('LinkedIn B2B Outreach', 'social', 3500.00, 2800.00, 89, 'active', '2026-06-15'),
  ('SMS Flash Sale', 'sms', 1200.00, 1200.00, 210, 'completed', '2026-05-01'),
  ('Google Ads Q3 Campaign', 'ads', 8000.00, 4500.00, 320, 'active', '2026-07-01'),
  ('Newsletter Welcome Series', 'email', 800.00, 450.00, 67, 'active', '2026-07-10'),
  ('Twitter Brand Awareness', 'social', 2000.00, 1800.00, 55, 'paused', '2026-04-15');

-- Sample Schedule Events
INSERT INTO schedule_events (title, event_date, event_time, duration_min, attendees, location, status) VALUES
  ('Team Standup', '2026-07-17', '09:00', 15, 'All Team', 'Zoom', 'upcoming'),
  ('Client Demo - TargetFlow', '2026-07-17', '14:00', 60, 'Anika Patel, Sales Team', 'Google Meet', 'upcoming'),
  ('Sprint Planning', '2026-07-18', '10:00', 90, 'Dev Team', 'Conference Room A', 'upcoming'),
  ('Marketing Review', '2026-07-18', '15:00', 45, 'Marketing Team', 'Zoom', 'upcoming'),
  ('Investor Update Call', '2026-07-19', '11:00', 30, 'CEO, CFO, Investors', 'Zoom', 'upcoming'),
  ('Product Roadmap Discussion', '2026-07-20', '10:00', 120, 'Product Team', 'Conference Room B', 'upcoming'),
  ('Sales Pipeline Review', '2026-07-21', '09:30', 60, 'Sales Team', 'Zoom', 'upcoming'),
  ('Q2 Results Presentation', '2026-07-15', '14:00', 90, 'All Company', 'Main Hall', 'completed'),
  ('Design Sprint Kickoff', '2026-07-14', '10:00', 120, 'Design Team', 'Studio', 'completed'),
  ('Vendor Negotiation', '2026-07-16', '16:00', 45, 'Procurement, Tom H.', 'Phone', 'cancelled');
